language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements/develop.txt
script:
  - py.test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: ilja_o
  password:
    secure: "GHQ6y8EilsMhLt41/lJUL2BYT7uKQFEAlKUFtyRPJasVKKYEJ3DLw34GPg0lyArBCcsuO0wXk1swulXbYn5lcD6dVhBveod01NIhvIVahkIcjvI9A26r4vIh7zJsKhG4+aJvMGSW8kAmLkIofhaFXgaKJD8WtqKD9NPApKteNFbctyWCxklPpyZ4XhQ42q0UyfyP54aSDM1tQtJMWVIzwvHCOiyFbPBRBkCoZsE6c4hND0pFllmGodvt9TFeBg/1R2du3L/wfaLvRc62SE5FfDPyOkvhZtCL32hDWkmGDeFG/JzvbGnJ8RKSijy+6kG88653gVJ85XiU3OFyYrto1XMQTNIhiOZeIZvHVYRpNDVW9erpWrcXG5KuSkQlR467w6J+OAMCiKG+LyT7rTsg7Y1Xz5lqxURd14ZTes8xDcH1sv8UMncblrpmEurkkVKvyb2Cqn3iH2XzXeLiKjJw1vnxPVuOd+5Ib37/X3ezyFN3YkuwD9NgKYHMrv4TnSuzMl+4L0RSDzdC03NFwTdtocvO2nfbkFTbz4EP5lmcJv6/2MhoX3QMgBBnUIGBa9EKD8oPmkwgJbzingZgfegtuQUk8PL8JjGGSyfAsMA9OZPffkUe7nahgphCwoV2q4ZYqkFoQ9KuhULVUlKxNDSCdU/hvFugJevaMp3Brlxm2uY="
  on:
    branch: production